export const GET_DATA_PHIM="GET_DATA_PHIM"
export const GET_DATA_RAP="GET_DATA_RAP"
export const GET_DATA_CUM_RAP="GET_DATA_CUM_RAP"
export const GET_DATA_LICH_CHIEU_PHIM='GET_DATA_LICH_CHIEU_PHIM'
export const LAY_THONG_TIN_DAT_VE='LAY_THONG_TIN_DAT_VE'
export const GET_DATA_USER='GET_DATA_USER'
export const SUA_NGUOI_DUNG="SUA_NGUOI_DUNG"
